
services:
  # 1. Your FastAPI Application
  fastapi_app:
    build: .
    container_name: inventory_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
      - mongo_db
    restart: always

  postgres_db:
    image: postgres:16
    container_name: inventory_postgres
    restart: always
    environment:
      POSTGRES_USER: lili
      POSTGRES_PASSWORD: lilian17
      POSTGRES_DB: inventory_db
    ports:
      - "5422:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
 
  mongo_db:
    image: mongo:7.0
    container_name: inventory_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lili
      MONGO_INITDB_ROOT_PASSWORD: lilian17
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
